services:
  - type: worker
    name: codex2050bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ALLOWED_USER_IDS
        value: "7416243786"
      - key: TEST_MODE
        value: "true"
